<a href="https://colab.research.google.com/github/YvesChu/Yves/blob/master/Musdall_0228.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Set

In [1]:
from google.colab import drive
drive.mount('/content/drive/')
!ls "/content/drive/My Drive/"
import os
path = "/content/drive/MyDrive/NewExp0228"

os.chdir(path)
os.listdir(path)

Mounted at /content/drive/
 0228.1.ipynb  'Colab Notebooks'   MusDataAug   Yating
 0228.ipynb     His		   NewExp0228


['fast-transformers', 'compound-word-transformer']

In [2]:
! /opt/bin/nvidia-smi

Mon Mar  8 17:02:32 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
os.chdir('/content/drive/MyDrive/NewExp0228/')
!git clone https://github.com/idiap/fast-transformers
!git clone https://github.com/YatingMusic/compound-word-transformer
os.chdir('/content/drive/MyDrive/NewExp0228/fast-transformers')
!python setup.py install

fatal: destination path 'fast-transformers' already exists and is not an empty directory.
fatal: destination path 'compound-word-transformer' already exists and is not an empty directory.
running install
running bdist_egg
running egg_info
writing pytorch_fast_transformers.egg-info/PKG-INFO
writing dependency_links to pytorch_fast_transformers.egg-info/dependency_links.txt
writing requirements to pytorch_fast_transformers.egg-info/requires.txt
writing top-level names to pytorch_fast_transformers.egg-info/top_level.txt
/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
writing manifest file 'pytorch_fast_transformers.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist

In [16]:
!pip install pycocotools numpy==1.16.0 opencv-python tqdm tensorboard tensorboardX pyyaml webcolors matplotlib
!pip install torch==1.7.1

!pip install madmom
!pip install chorder
!pip install miditoolkit

     |████████████████████████████████| 776.8MB 24kB/s 
  Found existing installation: torch 1.4.0
    Uninstalling torch-1.4.0:
      Successfully uninstalled torch-1.4.0


In [5]:
!pip install mido
!pip install muspy
import mido
import muspy
import random
import numpy as np
from mido import Message, MidiFile, MidiTrack

     |████████████████████████████████| 102kB 6.0MB/s 
     |████████████████████████████████| 5.6MB 39.2MB/s 
  Created wheel for pretty-midi: filename=pretty_midi-0.2.9-cp37-none-any.whl size=5591954 sha256=52bbf3affd397baf203bb027b650fd4b32f9fd737c0109e4e86844a91fe7bbc6
  Stored in directory: /root/.cache/pip/wheels/4c/a1/c6/b5697841db1112c6e5866d75a6b6bf1bef73b874782556ba66
Successfully built pretty-midi


# Aug

In [29]:
def mid2np(path):
  muspy_Music=muspy.read_midi(path)       #to muspy.Music
  numpy=muspy.to_note_representation(muspy_Music)#to numpy
  return numpy

def np2mid(path_gendir,numpy,sidx):
  muspy_Music=muspy.from_note_representation(numpy,resolution=275)#to muspy.Music
  # path_gendir_add = os.path.join(path_gendir,str(times))
  # os.mkdir(path_gendir_add)
  # path_outfiles = os.path.join(path_gendir_add,'get_{}.mid'.format(str(sidx)))
  path_outfiles = os.path.join(path_gendir,'get_{}.mid'.format(str(sidx)))
  muspy.write_midi(path_outfiles,muspy_Music)        #to mid

In [30]:
# def rand_noise(numpy):
#   line_num = np.shape(numpy)[0]
#   for obj in range (0,line_num):
#     prob = random.random()
#     if prob < 0.1:
#       noise_parameter=random.randint(-12,12)
#       arr=numpy[obj]
#       if arr[1]+noise_parameter>108:
#         arr[1]=108-noise_parameter
#       if arr[1]+noise_parameter<21:
#         arr[1]=21-noise_parameter
#       numpy=np.insert(numpy,obj,[arr[0],arr[1]+noise_parameter,arr[2],arr[3]],axis=0)
#   return numpy

In [31]:
def rand_del(numpy):
  line_num = np.shape(numpy)[0]
  for obj in range(0,line_num):
    prob = random.random()
    if prob < 0.1:
      numpy=np.delete(numpy,obj,axis=0)
  return numpy

def rand_add_3rd(numpy):
  line_num = np.shape(numpy)[0]
  for obj in range (0,line_num):
    prob=random.random()
    if prob < 0.02:
      arr=numpy[obj]
      if arr[1]+4>108:
        continue
      numpy = np.insert(numpy,obj,[arr[0],arr[1]+4,arr[2],arr[3]],axis=0)
  return numpy

def rand_add_5th(numpy):
  line_num = np.shape(numpy)[0]
  for obj in range (0,line_num):
    prob=random.random()
    if prob < 0.02:
      arr=numpy[obj]
      if arr[1]+7>108:
        continue
      numpy = np.insert(numpy,obj,[arr[0],arr[1]+7,arr[2],arr[3]],axis=0)
  return numpy

def rand_add_Oct(numpy):
  line_num = np.shape(numpy)[0]
  for obj in range (0,line_num):
    prob=random.random()
    if prob < 0.05:
      arr=numpy[obj]
      if arr[1]+12>108:
        continue
      numpy = np.insert(numpy,obj,[arr[0],arr[1]+12,arr[2],arr[3]],axis=0)
  return numpy

def pitch_shift_3rd(numpy):
  line_num = np.shape(numpy)[0]
  for obj in range (0,line_num):
    prob=random.random()
    if prob < 0.02:
      arr=numpy[obj]
      arr[1]+=4
      if arr[1]>108:
        arr[1]-=4
  return numpy

def pitch_shift_5th(numpy):
  line_num = np.shape(numpy)[0]
  for obj in range (0,line_num):
    prob=random.random()
    if prob < 0.02:
      arr=numpy[obj]
      arr[1]+=7
      if arr[1]>108:
        arr[1]-=7
  return numpy

def pitch_shift_Oct(numpy):
  line_num = np.shape(numpy)[0]
  for obj in range (0,line_num):
    prob=random.random()
    if prob < 0.05:
      arr=numpy[obj]
      arr[1]+=12
      if arr[1]>108:
        arr[1]-=12
  return numpy

In [32]:
def velocity_float(numpy):
  line_num = np.shape(numpy)[0]
  for obj in range(0,line_num):
    arr=numpy[obj]
    float_parameter=random.randint(-0.5,0.5)
    arr[3]+=float_parameter
  return numpy

def duration_float(numpy):
  line_num=np.shape(numpy)[0]
  for obj in range(0,line_num):
    arr=numpy[obj]
    float_parameter=random.randint(-0.5,0.5)
    arr[2]+=float_parameter
  return numpy 

In [33]:
def key_shift(numpy):
  line_num = np.shape(numpy)[0]
  key_shift=random.randint(-12,12)
  key_max=np.argmin(numpy[:,1])
  for obj in range(0,line_num):
    arr=numpy[obj]
    arr[1]+=key_shift
    if arr[1]>108:
      arr[1]=108
  return numpy

In [38]:
def circu(time,pathin,path_outfile,func):
  for sidx in range(0,time):

    path_gendir_add = os.path.join('/content/drive/MyDrive/MusDataAug/210217/01',str(time))
    # if not os.path.exists(path_ot):
    #   os.mkdir(path_gendir_add)
    # path_outfiles = os.path.join(path_gendir_add,'get_{}.mid'.format(str(sidx)))
    

    numpy = mid2np(pathin)
    numpy = func(numpy)
    np2mid(path_outfile,numpy,sidx)

In [ ]:
path_in = '/content/drive/MyDrive/MusDataAug/210217/Raw/07.mid'
path_ot = '/content/drive/MyDrive/MusDataAug/210309/New/00'
mode  = 'duration_float_0.5'
if not os.path.exists(path_ot):
    os.makedirs(path_ot)  

circu(5,path_in,path_ot,duration_float)

# Train

### 参数保存 Loss = 25
- baseline=(0,25)    exp/baseline.loss_25.0309
- (N,loss)=(70,25)   exp/N_70.loss_25.0309
- (N,loss)=(520,25)   exp/N_520.loss_25.0309
- rm=(0,25)       exp/rm.loss_25.0309

### 参数保存 Loss = 16
- baseline=(0,16)    exp/baseline.loss_16.0309
- (N,loss)=(70,16)   exp/N_70.loss_16.0309
- (N,loss)=(520,16)   exp/N_520.loss_16.0309
- rm=(0,16)       exp/rm.loss_16.0309

In [ ]:
os.chdir('/content/drive/MyDrive/NewExp0228/compound-word-transformer/workspace/uncond/cp-linear')
!python main-cp.py

# Generate 
song_num = 50

### 生成保存 Loss = 25
- baseline=(0,25)    gen_midis_baseline.loss_25.0309
- (N,loss)=(70,25)   gen_midis_N_70.loss_25.0309
- (N,loss)=(520,25)   gen_midis_N_520.loss_25.0309
- rm=(0,25)       gen_midis_rm.loss_25.0309

### 生成保存 Loss = 16
- baseline=(0,16)    gen_midis_baseline.loss_16.0309
- (N,loss)=(70,16)   gen_midis_N_70.loss_16.0309
- (N,loss)=(520,16)   gen_midis_N_520.loss_16.0309
- rm=(0,16)       gen_midis_rm.loss_16.0309

# Eva

In [8]:
import os
def docc(num_songs,path_ab):

  # num_songs = 30

  num = 0
  sc = np.zeros([num_songs,3])
  for info in os.listdir(path_ab):
    domain = os.path.abspath(path_ab)
    if not info == '.ipynb_checkpoints':
      info  = os.path.join(domain,info)
      # print(info)
      musicc=muspy.read_midi(info)
      m = muspy.scale_consistency(musicc)
      
      sc[num,0] = muspy.scale_consistency(musicc)

      sc[num,1] = muspy.pitch_class_entropy(musicc)
      sc[num,2] = muspy.pitch_entropy(musicc)
     
      # sc[num,5] = muspy.empty_beat_rate(musicc)
      # sc[num,3] = muspy.polyphony_rate(musicc, threshold=2)

      # sc[num,3] = muspy.polyphony_rate(musicc)
      # sc[num,4] = muspy.polyphony(musicc)

      # print(sc)
      # print(np.insert(sc,[0,1],m,axis=0))
      num = num + 1

  print(sc)   
  print('-'*49)
  print(np.median(sc,axis=0))

In [28]:
print('#'*49)
print('real')
print('#'*49)
docc(111,'/content/drive/MyDrive/Yating/dataset.0/midi_synchronized/src_001')

print('#'*49)
print('baseline=(0,25)')
print('#'*49)
docc(30,'/content/drive/MyDrive/NewExp0228/compound-word-transformer/workspace/uncond/cp-linear/gen_midis_baseline.loss_25.0309')

# print('#'*49)
# print('(N,loss)=(70,25)')
# print('#'*49)
# docc(30,'/content/drive/MyDrive/NewExp0228/compound-word-transformer/workspace/uncond/cp-linear/gen_midis_N_70.loss_25.0309')

print('#'*49)
print('(N,loss)=(520,25)')
print('#'*49)
docc(30,'/content/drive/MyDrive/NewExp0228/compound-word-transformer/workspace/uncond/cp-linear/gen_midis_N_520.loss_25.0309')

print('#'*49)
print('rm=(0,25)')
print('#'*49)
docc(30,'/content/drive/MyDrive/NewExp0228/compound-word-transformer/workspace/uncond/cp-linear/gen_midis_rm.loss_25.0309')

#################################################
real
#################################################
[[0.93641618 2.97249009 5.20577512]
 [0.95652174 2.89322685 4.92028886]
 [0.98924731 2.80243668 4.82239413]
 [0.97139452 2.8351752  5.03439082]
 [0.87981147 2.97691174 5.14459664]
 [0.91358025 3.0837389  5.31237814]
 [0.87659103 3.19646645 5.34183283]
 [0.87541713 3.22575055 5.10940427]
 [0.71412619 3.42702686 5.56992723]
 [0.75685786 3.43635525 5.53114342]
 [0.97582038 2.7936338  4.76499388]
 [0.93485915 2.99459876 5.12106325]
 [0.97482517 2.81815495 4.81754378]
 [0.99917184 2.79281281 5.09750488]
 [0.91002465 3.03734043 5.25570378]
 [0.97562674 2.87824863 4.9576444 ]
 [0.88164493 3.20894921 5.28101367]
 [0.78625452 3.26916318 5.50386957]
 [0.78551987 3.40391733 5.46132551]
 [0.71985234 3.48795778 5.62609474]
 [0.80287693 3.3543858  5.58458076]
 [0.82896652 3.24994613 5.52514575]
 [0.90047075 3.1072053  5.0730547 ]
 [0.88660742 3.16868616 5.43214066]
 [0.99375    2.72550746 4.77284

In [24]:
print('#'*49)
print('real')
print('#'*49)
docc(6,'/content/drive/MyDrive/MusDataAug/210217/Raw')

print('#'*49)
print('baseline=(0,16)')
print('#'*49)
docc(30,'/content/drive/MyDrive/NewExp0228/compound-word-transformer/workspace/uncond/cp-linear/gen_midis_baseline.loss_16.0309')

# print('#'*49)
# print('(N,loss)=(70,16)')
# print('#'*49)
# docc(30,'/content/drive/MyDrive/NewExp0228/compound-word-transformer/workspace/uncond/cp-linear/gen_midis_N_70.loss_16.0309')

print('#'*49)
print('(N,loss)=(520,16)')
print('#'*49)
docc(30,'/content/drive/MyDrive/NewExp0228/compound-word-transformer/workspace/uncond/cp-linear/gen_midis_N_520.loss_16.0309')

print('#'*49)
print('rm=(0,16)')
print('#'*49)
docc(30,'/content/drive/MyDrive/NewExp0228/compound-word-transformer/workspace/uncond/cp-linear/gen_midis_rm.loss_16.0309')

#################################################
real
#################################################
[[0.88247214 3.08378122 4.90578448]
 [0.92155984 3.06481534 4.65817347]
 [0.91039157 3.10732316 4.97776389]
 [0.77412281 3.24140796 5.38039841]
 [0.98889506 2.64291135 4.73215963]
 [0.82703566 3.24794408 5.05719227]]
-------------------------------------------------
[0.89643185 3.09555219 4.94177418]
#################################################
baseline=(0,16)
#################################################
[[0.72036235 3.40547669 5.37886659]
 [0.7601476  3.34798664 5.32423745]
 [0.74432863 3.37741364 5.31512877]
 [0.72829884 3.38447503 5.33727035]
 [0.77089649 3.37914695 5.32123964]
 [0.79093616 3.36986112 5.30961191]
 [0.78562903 3.30060889 5.28699943]
 [0.79509035 3.30319361 5.20919392]
 [0.68329909 3.40057334 5.39269375]
 [0.77902622 3.38019201 5.30296607]
 [0.73256791 3.36805284 5.3544507 ]
 [0.71975147 3.40892611 5.42349656]
 [0.72298066 3.35704959 5.32578397]
 [0.77656